#!/bin/bash
#skript, mis kontrollib kas PHP on olemas ja kui ei ole installeerib selle
#kontroll kas PHP on paigaldatud
a2=$(dpkg-query -W -f='${status}' php 2>/dev/null | grep -c "ok installed")
#kui ei ole installeeritud siis $a2 võrdub nulliga
if [ $a2 -eq 0 ]; then
#teavitab kasutajat php  installeerimisest
echo "Installeerib php"
#installeerimise rida
